controller_list:
  - name: iiwa/PositionJointInterface_trajectory_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: 
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
  - name: iiwa/gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    command_joint: robotiq_85_left_knuckle_joint
    joints: 
      - robotiq_85_left_knuckle_joint
